"""empty message

Revision ID: 1d38fcccdb84
Revises: 7903fc3eb043
Create Date: 2024-06-17 10:05:38.012319

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added
import data # added
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1d38fcccdb84'
down_revision = '7903fc3eb043'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'segments')
    op.drop_column('user', 'gifts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('gifts', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('segments', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###