"""empty message

Revision ID: c42f763a383a
Revises: 7b2517014f23
Create Date: 2025-10-08 07:52:44.012874

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added
import data # added


# revision identifiers, used by Alembic.
revision = 'c42f763a383a'
down_revision = '7b2517014f23'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blockedkeyword',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blockedkeyword_keyword'), 'blockedkeyword', ['keyword'], unique=False)
    op.create_index(op.f('ix_blockedkeyword_tenant_id'), 'blockedkeyword', ['tenant_id'], unique=False)
    op.create_table('moderationlog',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('content_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('keyword_block', 'user_block', 'content_flag', 'post_delete', 'comment_delete', name='moderationtype'), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('moderator_id', sa.Integer(), nullable=True),
    sa.Column('meta', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['moderator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moderationlog_moderator_id'), 'moderationlog', ['moderator_id'], unique=False)
    op.create_index(op.f('ix_moderationlog_tenant_id'), 'moderationlog', ['tenant_id'], unique=False)
    op.create_table('post',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('blocked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_blocked'), 'post', ['blocked'], unique=False)
    op.create_index(op.f('ix_post_tenant_id'), 'post', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_post_user_id'), 'post', ['user_id'], unique=False)
    op.create_table('userblock',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('moderator_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['moderator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userblock_moderator_id'), 'userblock', ['moderator_id'], unique=False)
    op.create_index(op.f('ix_userblock_tenant_id'), 'userblock', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_userblock_user_id'), 'userblock', ['user_id'], unique=True)
    op.create_table('comment',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parent_comment_id', sa.Integer(), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('blocked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_blocked'), 'comment', ['blocked'], unique=False)
    op.create_index(op.f('ix_comment_parent_comment_id'), 'comment', ['parent_comment_id'], unique=False)
    op.create_index(op.f('ix_comment_post_id'), 'comment', ['post_id'], unique=False)
    op.create_index(op.f('ix_comment_tenant_id'), 'comment', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_comment_user_id'), 'comment', ['user_id'], unique=False)
    op.create_table('reaction',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('like', 'salute', 'hug', name='reactiontype'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reaction_comment_id'), 'reaction', ['comment_id'], unique=False)
    op.create_index(op.f('ix_reaction_post_id'), 'reaction', ['post_id'], unique=False)
    op.create_index(op.f('ix_reaction_tenant_id'), 'reaction', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_reaction_user_id'), 'reaction', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reaction_user_id'), table_name='reaction')
    op.drop_index(op.f('ix_reaction_tenant_id'), table_name='reaction')
    op.drop_index(op.f('ix_reaction_post_id'), table_name='reaction')
    op.drop_index(op.f('ix_reaction_comment_id'), table_name='reaction')
    op.drop_table('reaction')
    op.drop_index(op.f('ix_comment_user_id'), table_name='comment')
    op.drop_index(op.f('ix_comment_tenant_id'), table_name='comment')
    op.drop_index(op.f('ix_comment_post_id'), table_name='comment')
    op.drop_index(op.f('ix_comment_parent_comment_id'), table_name='comment')
    op.drop_index(op.f('ix_comment_blocked'), table_name='comment')
    op.drop_table('comment')
    op.drop_index(op.f('ix_userblock_user_id'), table_name='userblock')
    op.drop_index(op.f('ix_userblock_tenant_id'), table_name='userblock')
    op.drop_index(op.f('ix_userblock_moderator_id'), table_name='userblock')
    op.drop_table('userblock')
    op.drop_index(op.f('ix_post_user_id'), table_name='post')
    op.drop_index(op.f('ix_post_tenant_id'), table_name='post')
    op.drop_index(op.f('ix_post_blocked'), table_name='post')
    op.drop_table('post')
    op.drop_index(op.f('ix_moderationlog_tenant_id'), table_name='moderationlog')
    op.drop_index(op.f('ix_moderationlog_moderator_id'), table_name='moderationlog')
    op.drop_table('moderationlog')
    op.drop_index(op.f('ix_blockedkeyword_tenant_id'), table_name='blockedkeyword')
    op.drop_index(op.f('ix_blockedkeyword_keyword'), table_name='blockedkeyword')
    op.drop_table('blockedkeyword')
    # ### end Alembic commands ###