"""add anonymous_likes_count to post and comment

Revision ID: a1b2c3d4e5f6
Revises: 16ecaec6fb01
Create Date: 2025-11-27 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '16ecaec6fb01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('anonymous_likes_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('comment', sa.Column('anonymous_likes_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'anonymous_likes_count')
    op.drop_column('post', 'anonymous_likes_count')
    # ### end Alembic commands ###
