"""empty message

Revision ID: 16ecaec6fb01
Revises: c42f763a383a
Create Date: 2025-11-12 22:00:47.653966

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added
import data # added


# revision identifiers, used by Alembic.
revision = '16ecaec6fb01'
down_revision = 'c42f763a383a'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant',
    sa.Column('Tenant', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('domains', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Tenant')
    )
    op.add_column('user', sa.Column('tenant_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'tenant_id')
    op.drop_table('tenant')
    # ### end Alembic commands ###