"""empty message

Revision ID: ac2e421f0373
Revises: 893e6a1b7aa7
Create Date: 2025-03-19 21:56:39.611771

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added
import data # added


# revision identifiers, used by Alembic.
revision = 'ac2e421f0373'
down_revision = '893e6a1b7aa7'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('stripe_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('payment_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'payment_status')
    op.drop_column('user', 'stripe_id')
    # ### end Alembic commands ###